version: '2'
services:
  superscript:
    build: .
    environment:
      - SLACK_TOKEN
      - MONGO_URI=mongodb://mongo/superscriptDB
    volumes:
      - ./plugins:/opt/superscript/plugins
      - ./topics:/opt/superscript/topics
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
     - ./mongo:/data/db
